apiVersion: openchoreo.dev/v1alpha1
kind: SecretReference
metadata:
  name: openai-credentials
  namespace: default
spec:
  template:
    type: Opaque
  data:
    - secretKey: apiKey
      remoteRef:
        key: fhir-canvas-explorer-openai-api-key
        property: value
  refreshInterval: 1h
