apiVersion: openchoreo.dev/v1alpha1
kind: Workload
metadata:
  name: fhir-server
  namespace: default
spec:
  owner:
    projectName: fhir-canvas-explorer
    componentName: fhir-server
  endpoints:
    http:
      type: HTTP
      port: 9090
      visibility: [project]
  dependencies:
    resources:
      - ref: fhir-postgres
        envBindings:
          host: DB_HOST
          port: DB_PORT
          username: DB_USER
          password: DB_PASSWORD
          database: DB_NAME
  container:
    image: ghcr.io/prdai-archive/wso2-fhir-server:latest
    env:
      - key: SERVER_PORT
        value: "9090"
      - key: BASE_URL
        value: http://fhir-server:9090/fhir/r4
      - key: LOG_LEVEL
        value: info
      - key: FHIR_CREATE_TABLES
        value: "true"
